### ISSUE TITLE
Broken Persona 5 Theme

### ISSUE THREAD

**Issue by ghost** [ZackyGameDev/BetterDiscordThemes#1]
The persona 5 theme looks like the default base theme it was forked off of with a lot of glitches. is it possible to get it fixed?

**Comment by ZackyGameDev** [comment]
This fun project of mine is very, very old, discord has updated it's GUI many many times since then, that is why this theme doesn't work anymore. Unfortunately I don't plan on updating this old project any time soon, because not only am I somewhat busy now, even if I update it, it will probably need another update after a month or so anyway

**Comment by ZackyGameDev** [comment]
(also because my persona 5 fan phase is over, so I also lack motivation)

**Comment by ghost** [comment]
I see. Well, thank you for atleast making the theme and good luck with your further projects! I hope to see you around sometime Zacky
